---
- name: Init New Server
  hosts: Server
#  sudo: yes

# Default Linux user
  vars:
    default_user: web
    default_project_name: project

  roles:
    - upgrade
    - useradd
    - package
    - php-fpm
    - nginx
    - composer
    - xdebug