---
- name: Get Composer
  sudo: yes
  shell:
    curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

- name: Add assets
  sudo: yes
  command: composer global require "fxp/composer-asset-plugin:@dev"