---
# Add SWAP
# fallocate -l 4G /swapfile
# chmod 600 /swapfile
# mkswap /swapfile
# swapon /swapfile
# echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
# sysctl vm.swappiness=10
# echo "vm.swappiness=10" >> /etc/sysctl.conf
- name: Install Mysql
  apt: pkg="{{item}}" state=latest update_cache=yes
  sudo: yes
  with_items:
  - mysql-server-5.6
  - php5-mysql


- name: Start the MySQL service
  sudo: yes
  service:
    name: mysql
    state: started
    enabled: true

#- name: update mysql root password for all root accounts
#  sudo: yes
#  mysql_user:
#    name: root
#    host: "{{ item }}"
#    password: "1234"
#    login_user: root
#    login_password: "1234"
#    check_implicit_admin: yes
#    priv: "*.*:ALL,GRANT"
#  with_items:
#    - 127.0.0.1
#    - ::1
#    - localhost